### ISSUE TITLE
Support simple ASCII/Emoji icons as marker symbols in Leaflet YAML

### ISSUE THREAD

**Issue by karkem** [jim-fx/silverbullet-leaflet#1]
Feature Request:

I’d like to suggest a simple enhancement for the leaflet code block in Silverbullet:
Enable support for inline ASCII or emoji icons as visible marker symbols on the map.

Motivation:
Currently, we can add a title to a marker like this:

```yaml
markers:
  - lat: 59.1153596
    lng: 12.186088
    title: Herrenäs
```

…but the marker always uses the default Leaflet pin.

In many use cases (e.g. personal notes, travel logs, mapping places of interest), it would be great to customize the visible map marker itself with simple ASCII characters or emoji (e.g. 🏠, 🏕️, 🛶).

Suggested YAML syntax:

Something like:

```yaml
markers:
  - lat: 59.1153596
    lng: 12.186088
    title: Herrenäs
    icon: "🏠"
    iconSize: [24, 24] 
```

This would render an Icon with the given emoji or ASCII content – super lightweight, offline-friendly, and no external dependencies needed.

Benefits:
Zero setup: no JavaScript, no uploads
Works offline and in self-hosted/private Silverbullet installations
Makes maps more expressive with minimal effort

Thanks!
