### ISSUE TITLE
Support for Color Configuration in Polylines

### ISSUE THREAD

**Issue by karkem** [jim-fx/silverbullet-leaflet#3]
Currently, it's possible to define polylines like this:

```yaml

polylines:
  - name: TestLine
    points:
      - [59.025009, 12.225037]
      - [59.025109, 12.225337]
      - [59.025209, 12.224837]
```

It would be very useful to have the ability to configure the color of each polyline. For example:

```yaml

polylines:
  - name: TestLine
    color: "#FF0000"
    points:
      - [59.025009, 12.225037]
      - [59.025109, 12.225337]
      - [59.025209, 12.224837]
```

Benefits:

Improved visual distinction between multiple lines

More flexibility for users customizing map displays

Implementation Suggestion:

Add an optional color property (e.g., as a HEX value #RRGGBB or just named color like in the icons)

Use a default color (e.g., black) if color is not provided

Thanks in advance! :)
